//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.26 at 07:56:33 PM YEKT 
//


package ru.mail.fortune.webservices.internetmagazine.goods;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ru.mail.fortune.webservices.internetmagazine.goods package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ru.mail.fortune.webservices.internetmagazine.goods
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DeleteGoodsGroupRequest }
     * 
     */
    public DeleteGoodsGroupRequest createDeleteGoodsGroupRequest() {
        return new DeleteGoodsGroupRequest();
    }

    /**
     * Create an instance of {@link GetAllGoodsGroupsResponse }
     * 
     */
    public GetAllGoodsGroupsResponse createGetAllGoodsGroupsResponse() {
        return new GetAllGoodsGroupsResponse();
    }

    /**
     * Create an instance of {@link GoodsGroupXml }
     * 
     */
    public GoodsGroupXml createGoodsGroupXml() {
        return new GoodsGroupXml();
    }

    /**
     * Create an instance of {@link DeleteGoodsResponse }
     * 
     */
    public DeleteGoodsResponse createDeleteGoodsResponse() {
        return new DeleteGoodsResponse();
    }

    /**
     * Create an instance of {@link DeleteGoodsGroupResponse }
     * 
     */
    public DeleteGoodsGroupResponse createDeleteGoodsGroupResponse() {
        return new DeleteGoodsGroupResponse();
    }

    /**
     * Create an instance of {@link DeleteGoodsBasketResponse }
     * 
     */
    public DeleteGoodsBasketResponse createDeleteGoodsBasketResponse() {
        return new DeleteGoodsBasketResponse();
    }

    /**
     * Create an instance of {@link TestIsOkResponse }
     * 
     */
    public TestIsOkResponse createTestIsOkResponse() {
        return new TestIsOkResponse();
    }

    /**
     * Create an instance of {@link InsertGoodsResponse }
     * 
     */
    public InsertGoodsResponse createInsertGoodsResponse() {
        return new InsertGoodsResponse();
    }

    /**
     * Create an instance of {@link GetAllGoodsGroupsRequest }
     * 
     */
    public GetAllGoodsGroupsRequest createGetAllGoodsGroupsRequest() {
        return new GetAllGoodsGroupsRequest();
    }

    /**
     * Create an instance of {@link InsertGoodsGroupResponse }
     * 
     */
    public InsertGoodsGroupResponse createInsertGoodsGroupResponse() {
        return new InsertGoodsGroupResponse();
    }

    /**
     * Create an instance of {@link GoodsXml }
     * 
     */
    public GoodsXml createGoodsXml() {
        return new GoodsXml();
    }

    /**
     * Create an instance of {@link ActionStatus }
     * 
     */
    public ActionStatus createActionStatus() {
        return new ActionStatus();
    }

    /**
     * Create an instance of {@link Basket2GoodsXml }
     * 
     */
    public Basket2GoodsXml createBasket2GoodsXml() {
        return new Basket2GoodsXml();
    }

    /**
     * Create an instance of {@link InsertGoodsBasketResponse }
     * 
     */
    public InsertGoodsBasketResponse createInsertGoodsBasketResponse() {
        return new InsertGoodsBasketResponse();
    }

    /**
     * Create an instance of {@link InsertGoodsGroupRequest }
     * 
     */
    public InsertGoodsGroupRequest createInsertGoodsGroupRequest() {
        return new InsertGoodsGroupRequest();
    }

    /**
     * Create an instance of {@link GetBasketsByPeriodResponse }
     * 
     */
    public GetBasketsByPeriodResponse createGetBasketsByPeriodResponse() {
        return new GetBasketsByPeriodResponse();
    }

    /**
     * Create an instance of {@link GetBasketsByPeriodRequest }
     * 
     */
    public GetBasketsByPeriodRequest createGetBasketsByPeriodRequest() {
        return new GetBasketsByPeriodRequest();
    }

    /**
     * Create an instance of {@link DeleteGoodsBasketRequest }
     * 
     */
    public DeleteGoodsBasketRequest createDeleteGoodsBasketRequest() {
        return new DeleteGoodsBasketRequest();
    }

    /**
     * Create an instance of {@link InsertGoodsBasketRequest }
     * 
     */
    public InsertGoodsBasketRequest createInsertGoodsBasketRequest() {
        return new InsertGoodsBasketRequest();
    }

    /**
     * Create an instance of {@link TestIsOkRequest }
     * 
     */
    public TestIsOkRequest createTestIsOkRequest() {
        return new TestIsOkRequest();
    }

    /**
     * Create an instance of {@link GoodsBasketXml }
     * 
     */
    public GoodsBasketXml createGoodsBasketXml() {
        return new GoodsBasketXml();
    }

    /**
     * Create an instance of {@link InsertGoodsRequest }
     * 
     */
    public InsertGoodsRequest createInsertGoodsRequest() {
        return new InsertGoodsRequest();
    }

    /**
     * Create an instance of {@link DeleteGoodsRequest }
     * 
     */
    public DeleteGoodsRequest createDeleteGoodsRequest() {
        return new DeleteGoodsRequest();
    }

}
