//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.26 at 07:56:33 PM YEKT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://ru/mail/fortune/webservices/internetmagazine/goods", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ru.mail.fortune.webservices.internetmagazine.goods;
